export const DIVISIONS = [
  "Finance division",
  "Aktuaris perusahaan",
  "Accounting division",
  "Client market & treaty P&C division",
  "Business management division",
  "Reinsurance & product underwriting P&C division",
  "Client market & pricing actuary L&H division",
  "Underwriting center & risk engineering dept",
  "Legal, compliance and risk management division",
  "Corporate secretary division",
  "TJSL & ESG division",
  "Human capital & general affair division",
  "Information technology division",
  "Strategic development division",
  "Indonesia Re Institute",
  "Internal auditor",
  "Corporate transformation management office",
] as const;